(()=>{
const CACHE=new Map();
function eventForCard(el){if(typeof rawEvents!=='function')return null;const events=rawEvents();if(typeof eventKey==='function'){const exact=events.find(e=>eventKey(e)===el.dataset.eventKey);if(exact)return exact}const who=(el.querySelector('.who')?.textContent||'').trim(),timeStart=((el.querySelector('.time')?.textContent||'').match(/\d{1,2}:\d{2}/)||[])[0]||'',dateTxt=(el.querySelector('.top div div:nth-child(2)')?.textContent||'').trim();return events.filter(e=>!who||e.child===who).find(e=>{const d=new Date(e.date+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'}).replace(/,$/,'');return (!dateTxt||d===dateTxt)&&(!timeStart||String(e.time||'').includes(timeStart))})||null}
function venueGeo(q){const s=String(q||'').toLowerCase();if(s.includes('am plänterwald')||s.includes('am plaenterwald')||s.includes('tzpw'))return{lat:52.47878,lon:13.46912};if(s.includes('bruno-bürgel-weg')||s.includes('bruno-buergel-weg')||s.includes('tzo'))return{lat:52.45291,lon:13.53771};if(s.includes('neue krugallee')||/(^|\W)nk($|\W)/.test(s))return{lat:52.47855,lon:13.48408};if(s.includes('oschatzer ring'))return{lat:52.5417,lon:13.5946};if(s.includes('melanchthonstraße')||s.includes('melanchthonstrasse')||s.includes('rosenhag'))return{lat:52.5095,lon:13.6157};if(s.includes('allee der kosmonauten'))return{lat:52.5269,lon:13.5238};return null}
function clean(q){return String(q||'').replace(/\([^)]*\)/g,' ').replace(/\bdeutschland\b/ig,' ').replace(/\s+/g,' ').trim()}
async function geocode(q){const known=venueGeo(q);if(known)return known;const key=clean(q);if(!key)return null;if(CACHE.has('g:'+key))return CACHE.get('g:'+key);const p=(async()=>{try{for(const query of [key,key+', Deutschland']){const u='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=de&q='+encodeURIComponent(query);const r=await fetch(u,{cache:'no-store',headers:{Accept:'application/json'}});if(!r.ok)continue;const j=await r.json();if(j&&j[0])return{lat:Number(j[0].lat),lon:Number(j[0].lon)}}}catch(_){}return null})();CACHE.set('g:'+key,p);return p}
function icon(c){if(c===0)return'☀️';if([1,2].includes(c))return'🌤️';if(c===3)return'☁️';if([45,48].includes(c))return'🌫️';if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(c))return'🌧️';if([71,73,75,77,85,86].includes(c))return'🌨️';if([95,96,99].includes(c))return'⛈️';return'🌦️'}
async function precise(e,geo){const tm=(String(e.time||'').match(/(\d{1,2}):(\d{2})/)||[]);if(!tm.length)return'';const min=Number(tm[1])*60+Number(tm[2]),hour=Math.max(0,Math.min(23,Math.round(min/60))),slot=`${e.date}T${String(hour).padStart(2,'0')}:00`,key=`w:${geo.lat.toFixed(3)},${geo.lon.toFixed(3)}:${slot}`;if(CACHE.has(key))return CACHE.get(key);const p=(async()=>{try{const u=`https://api.open-meteo.com/v1/forecast?latitude=${geo.lat}&longitude=${geo.lon}&hourly=temperature_2m,apparent_temperature,precipitation_probability,weather_code,wind_speed_10m&timezone=Europe%2FBerlin&forecast_days=9`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)return'';const j=await r.json(),h=j.hourly||{},i=(h.time||[]).indexOf(slot);if(i<0)return'';const t=Math.round(h.temperature_2m[i]),f=Math.round(h.apparent_temperature[i]),rain=Math.round(h.precipitation_probability[i]),wind=Math.round(h.wind_speed_10m[i]),code=Number(h.weather_code[i]);return `${icon(code)} Zum Beginn ${tm[1].padStart(2,'0')}:${tm[2]} Uhr: ${t} °C · gefühlt ${f} °C · Regen ${rain}% · Wind ${wind} km/h`}catch(_){return''}})();CACHE.set(key,p);return p}
async function update(){const cards=[...document.querySelectorAll('.card[data-event-key]')];await Promise.all(cards.map(async el=>{const line=el.querySelector('.smartline.weather');if(!line)return;const e=eventForCard(el);if(!e||!e.location)return;const geo=await geocode(e.location);if(!geo)return;const txt=await precise(e,geo);if(txt)line.textContent=txt}))}
setTimeout(update,700);setTimeout(update,1800);setInterval(update,5000);document.addEventListener('click',()=>setTimeout(update,300),{passive:true});
})();