(()=>{
'use strict';
const GEO_CACHE=new Map(),WX_CACHE=new Map();
let currentPos=null,busy=false;
const css=`
.smartbar{display:flex;gap:7px;align-items:center;margin:0 0 10px}.smartbar button{font-size:11px;padding:8px 11px}.smartbar .smartstatus{font-size:10px;color:#6e6e73;font-weight:700}.smartinfo{display:grid;gap:5px;margin-top:8px}.smartline{font-size:10px;font-weight:800;line-height:1.3;background:rgba(255,255,255,.76);border-radius:9px;padding:6px 7px}.smartline.weather{font-weight:750}@media(max-width:560px){.smartbar{gap:5px}.smartbar button{font-size:10px;padding:7px 9px}.smartline{font-size:9px;padding:5px 6px}}
`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function addBar(){if(document.querySelector('#smartbar'))return;const stats=document.querySelector('#stats');if(!stats)return;const bar=document.createElement('div');bar.className='smartbar';bar.id='smartbar';bar.innerHTML=`<button id="smartLocBtn">📍 Standort aktualisieren</button><span class="smartstatus" id="smartStatus">Abfahrt vom aktuellen Standort</span>`;stats.insertAdjacentElement('afterend',bar);document.querySelector('#smartLocBtn').onclick=()=>locate(true)}
function setStatus(t){const e=document.querySelector('#smartStatus');if(e)e.textContent=t}
function locate(userAction=false){if(!navigator.geolocation){setStatus('Standort nicht unterstützt');return}setStatus('Standort wird ermittelt …');navigator.geolocation.getCurrentPosition(p=>{currentPos={lat:p.coords.latitude,lon:p.coords.longitude,at:Date.now()};try{localStorage.setItem('smartLocation','1')}catch(_){}setStatus('Standort aktiv · aktualisiert');refreshCards(true)},err=>{setStatus(err&&err.code===1?'Standortfreigabe fehlt':'Standort momentan nicht verfügbar');if(userAction&&err&&err.code===1)try{localStorage.removeItem('smartLocation')}catch(_){}} ,{enableHighAccuracy:true,maximumAge:60000,timeout:12000})}
function parseTime(s){const m=String(s||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}
function minusTime(base,mins){const n=parseTime(base);if(n===null)return'';let x=n-mins;while(x<0)x+=1440;return `${String(Math.floor(x/60)%24).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`}
function hav(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b),x=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function driveEstimate(km){if(km<2)return Math.max(6,Math.round(km/18*60+4));if(km<8)return Math.round(km/27*60+5);if(km<20)return Math.round(km/36*60+6);if(km<50)return Math.round(km/48*60+8);return Math.round(km/72*60+12)}
function knownVenue(q){const s=String(q||'').toLowerCase();if(s.includes('am plänterwald')||s.includes('am plaenterwald')||s.includes('tzpw'))return{lat:52.47878,lon:13.46912};if(s.includes('bruno-bürgel-weg')||s.includes('bruno-buergel-weg')||s.includes('tzo'))return{lat:52.45291,lon:13.53771};if(s.includes('neue krugallee')||/(^|\W)nk($|\W)/.test(s))return{lat:52.47855,lon:13.48408};return null}
function cleanVenue(q){return String(q||'').replace(/\([^)]*\)/g,' ').replace(/\bzugang\b[^,]*/ig,' ').replace(/\s+/g,' ').replace(/\s+,/g,',').trim()}
async function geocode(q){q=String(q||'').trim();if(!q)return null;const known=knownVenue(q);if(known)return known;if(GEO_CACHE.has(q))return GEO_CACHE.get(q);const p=(async()=>{try{const clean=cleanVenue(q),queries=[clean,q,clean+' Deutschland'];for(const query of [...new Set(queries.filter(Boolean))]){const u='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=de&q='+encodeURIComponent(query);const r=await fetch(u,{cache:'no-store',headers:{'Accept':'application/json'}});if(!r.ok)continue;const j=await r.json();if(j&&j[0])return{lat:Number(j[0].lat),lon:Number(j[0].lon)}}}catch(_){}return null})();GEO_CACHE.set(q,p);return p}
function wxIcon(c){if(c===0)return'☀️';if([1,2].includes(c))return'🌤️';if(c===3)return'☁️';if([45,48].includes(c))return'🌫️';if([51,53,55,56,57,61,63,65,66,67,80,81,82].includes(c))return'🌧️';if([71,73,75,77,85,86].includes(c))return'🌨️';if([95,96,99].includes(c))return'⛈️';return'🌦️'}
async function weather(e,geo){const key=`${geo.lat.toFixed(3)},${geo.lon.toFixed(3)}|${e.date}`;if(WX_CACHE.has(key))return WX_CACHE.get(key);const p=(async()=>{try{const now=new Date();now.setHours(0,0,0,0);const d=new Date(e.date+'T12:00:00');if(d<now||(d-now)>8*86400000)return'';const u=`https://api.open-meteo.com/v1/forecast?latitude=${geo.lat}&longitude=${geo.lon}&daily=weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max&timezone=auto&forecast_days=9`;const r=await fetch(u,{cache:'no-store'});if(!r.ok)return'';const j=await r.json(),x=j.daily||{},i=(x.time||[]).indexOf(e.date);if(i<0)return'';const lo=Math.round(x.temperature_2m_min[i]),hi=Math.round(x.temperature_2m_max[i]),rain=x.precipitation_probability_max[i],code=x.weather_code[i];return `${wxIcon(code)} Wetter am Terminort: ${lo}–${hi} °C${Number.isFinite(rain)?` · Regen ${rain}%`:''}`}catch(_){return''}})();WX_CACHE.set(key,p);return p}
function ensureBox(el){let box=el.querySelector('.smartinfo');if(box)return box;box=document.createElement('div');box.className='smartinfo';const target=el.querySelector('.maps')||el.querySelector('.rsvp');if(target)target.before(box);else el.appendChild(box);box.innerHTML='<div class="smartline">⏳ Wetter & Abfahrt werden geladen …</div>';return box}
function cardHints(el){const who=(el.querySelector('.who')?.textContent||'').trim();const dateTxt=(el.querySelector('.top div div:nth-child(2)')?.textContent||'').trim();const timeTxt=(el.querySelector('.time')?.textContent||'').trim();return{who,dateTxt,timeTxt}}
function eventForCard(el){if(typeof rawEvents!=='function')return null;const events=rawEvents();if(typeof eventKey==='function'){const exact=events.find(e=>eventKey(e)===el.dataset.eventKey);if(exact)return exact}const h=cardHints(el);const candidates=events.filter(e=>!h.who||e.child===h.who);if(!candidates.length)return null;const timeStart=(h.timeTxt.match(/\d{1,2}:\d{2}/)||[])[0]||'';return candidates.find(e=>{const d=new Date(e.date+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'}).replace(/,$/,'');return (!h.dateTxt||d===h.dateTxt)&&(!timeStart||String(e.time||'').includes(timeStart))})||null}
async function enhanceCard(el){const box=ensureBox(el),e=eventForCard(el);if(!e){box.innerHTML='<div class="smartline">⚠️ Termin konnte nicht zugeordnet werden</div>';return}if(!e.location){box.innerHTML='<div class="smartline">📍 Kein Terminort hinterlegt</div>';return}const geo=await geocode(e.location);if(!geo){box.innerHTML='<div class="smartline">📍 Terminort konnte nicht aufgelöst werden</div>';return}const lines=[];const w=await weather(e,geo);if(w)lines.push(`<div class="smartline weather">${w}</div>`);if(currentPos){const km=hav(currentPos.lat,currentPos.lon,geo.lat,geo.lon),mins=driveEstimate(km),base=e.meetTime||e.meetingTime||e.treffzeit||e.time||'',depart=minusTime(base,mins+10);if(depart)lines.push(`<div class="smartline">🚗 ca. ${mins} Min · Abfahrt ${depart} Uhr <span style="opacity:.65;font-weight:650">(+10 Min Puffer)</span></div>`)}else lines.push(`<div class="smartline">📍 Standort aktualisieren für Abfahrtszeit</div>`);box.innerHTML=lines.join('')||'<div class="smartline">Wetterdaten momentan nicht verfügbar</div>'}
async function refreshCards(force=false){if(busy&&!force)return;busy=true;try{addBar();const cards=[...document.querySelectorAll('.card[data-event-key]')];cards.forEach(ensureBox);await Promise.all(cards.slice(0,40).map(c=>enhanceCard(c)))}finally{busy=false}}
addBar();setTimeout(()=>refreshCards(true),500);setTimeout(()=>locate(false),900);setInterval(()=>refreshCards(false),4000);document.addEventListener('click',()=>setTimeout(()=>refreshCards(false),150),{passive:true});setInterval(()=>{if(currentPos&&Date.now()-currentPos.at>5*60*1000)locate(false)},60000);
})();