(()=>{
'use strict';
const GEO_CACHE=new Map();let currentPos=null,busy=false;
function eventEnd(e){const start=String(e.time||'').match(/(\d{1,2}):(\d{2})/),end=String(e.endTime||'').match(/(\d{1,2}):(\d{2})/);if(!e.date)return new Date(0);let hh=23,mm=59;if(end){hh=+end[1];mm=+end[2]}else if(start){const total=+start[1]*60+(+start[2])+120;hh=Math.floor(total/60)%24;mm=total%60}return new Date(`${e.date}T${String(hh).padStart(2,'0')}:${String(mm).padStart(2,'0')}:00`)}
function expired(e){return eventEnd(e)<new Date()}
if(typeof futureEvents==='function')futureEvents=()=>rawEvents().filter(e=>!expired(e));
if(typeof allFilteredEvents==='function')allFilteredEvents=()=>{let ev=rawEvents().filter(e=>!expired(e));if(filter!=='all')ev=ev.filter(e=>e.child===filter);return ev};
if(typeof pastEvents==='function')pastEvents=()=>rawEvents().filter(e=>expired(e)).sort((a,b)=>eventEnd(b)-eventEnd(a));
const css=`.smartbar{display:flex;gap:7px;align-items:center;margin:0 0 10px}.smartbar button{font-size:11px;padding:8px 11px}.smartbar .smartstatus{font-size:10px;color:#6e6e73;font-weight:700}.smartinfo{display:grid;gap:5px;margin-top:8px}.smartline{font-size:10px;font-weight:800;line-height:1.3;background:rgba(255,255,255,.76);border-radius:9px;padding:6px 7px}.smartline.weather{font-weight:750}@media(max-width:560px){.smartbar{gap:5px}.smartbar button{font-size:10px;padding:7px 9px}.smartline{font-size:9px;padding:5px 6px}}`;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function addBar(){if(document.querySelector('#smartbar'))return;const stats=document.querySelector('#stats');if(!stats)return;const bar=document.createElement('div');bar.className='smartbar';bar.id='smartbar';bar.innerHTML=`<button id="smartLocBtn">📍 Standort aktualisieren</button><span class="smartstatus" id="smartStatus">Abfahrt vom aktuellen Standort</span>`;stats.insertAdjacentElement('afterend',bar);document.querySelector('#smartLocBtn').onclick=()=>locate(true)}function setStatus(t){const e=document.querySelector('#smartStatus');if(e)e.textContent=t}
function locate(userAction=false){if(!navigator.geolocation){setStatus('Standort nicht unterstützt');return}setStatus('Standort wird ermittelt …');navigator.geolocation.getCurrentPosition(p=>{currentPos={lat:p.coords.latitude,lon:p.coords.longitude,at:Date.now()};try{localStorage.setItem('smartLocation','1')}catch(_){}setStatus('Standort aktiv · aktualisiert');refreshCards(true)},err=>{setStatus(err&&err.code===1?'Standortfreigabe fehlt':'Standort momentan nicht verfügbar');if(userAction&&err&&err.code===1)try{localStorage.removeItem('smartLocation')}catch(_){}} ,{enableHighAccuracy:true,maximumAge:60000,timeout:12000})}
function parseTime(s){const m=String(s||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null}function minusTime(base,mins){const n=parseTime(base);if(n===null)return'';let x=n-mins;while(x<0)x+=1440;return `${String(Math.floor(x/60)%24).padStart(2,'0')}:${String(x%60).padStart(2,'0')}`}
function hav(a,b,c,d){const R=6371,r=x=>x*Math.PI/180,dl=r(c-a),dn=r(d-b),x=Math.sin(dl/2)**2+Math.cos(r(a))*Math.cos(r(c))*Math.sin(dn/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}function driveEstimate(km){if(km<2)return Math.max(6,Math.round(km/18*60+4));if(km<8)return Math.round(km/27*60+5);if(km<20)return Math.round(km/36*60+6);if(km<50)return Math.round(km/48*60+8);return Math.round(km/72*60+12)}
function knownVenue(q){const s=String(q||'').toLowerCase();if(s.includes('am plänterwald')||s.includes('am plaenterwald')||s.includes('tzpw'))return{lat:52.47878,lon:13.46912};if(s.includes('bruno-bürgel-weg')||s.includes('bruno-buergel-weg')||s.includes('tzo'))return{lat:52.45291,lon:13.53771};if(s.includes('neue krugallee')||/(^|\W)nk($|\W)/.test(s))return{lat:52.47855,lon:13.48408};if(s.includes('oschatzer ring'))return{lat:52.5417,lon:13.5946};if(s.includes('melanchthonstraße')||s.includes('melanchthonstrasse')||s.includes('rosenhag'))return{lat:52.5095,lon:13.6157};if(s.includes('allee der kosmonauten'))return{lat:52.5269,lon:13.5238};return null}function cleanVenue(q){return String(q||'').replace(/\([^)]*\)/g,' ').replace(/\bzugang\b[^,]*/ig,' ').replace(/\s+/g,' ').replace(/\s+,/g,',').trim()}
async function geocode(q){q=String(q||'').trim();if(!q)return null;const known=knownVenue(q);if(known)return known;if(GEO_CACHE.has(q))return GEO_CACHE.get(q);const p=(async()=>{try{const clean=cleanVenue(q),queries=[clean,q,clean+' Deutschland'];for(const query of [...new Set(queries.filter(Boolean))]){const u='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=de&q='+encodeURIComponent(query);const r=await fetch(u,{cache:'no-store',headers:{'Accept':'application/json'}});if(!r.ok)continue;const j=await r.json();if(j&&j[0])return{lat:Number(j[0].lat),lon:Number(j[0].lon)}}}catch(_){}return null})();GEO_CACHE.set(q,p);return p}
function ensureBox(el){let box=el.querySelector('.smartinfo');if(box)return box;box=document.createElement('div');box.className='smartinfo';const target=el.querySelector('.maps')||el.querySelector('.rsvp');if(target)target.before(box);else el.appendChild(box);box.innerHTML='<div class="smartline weather">🌦️ Wetter zum Terminbeginn wird geladen …</div><div class="smartline">📍 Standort aktualisieren für Abfahrtszeit</div>';return box}
function eventForCard(el){if(typeof rawEvents!=='function')return null;const events=rawEvents();if(typeof eventKey==='function'){const exact=events.find(e=>eventKey(e)===el.dataset.eventKey);if(exact)return exact}const who=(el.querySelector('.who')?.textContent||'').trim(),timeStart=((el.querySelector('.time')?.textContent||'').match(/\d{1,2}:\d{2}/)||[])[0]||'',dateTxt=(el.querySelector('.top div div:nth-child(2)')?.textContent||'').trim();return events.filter(e=>!who||e.child===who).find(e=>{const d=new Date(e.date+'T12:00:00').toLocaleDateString('de-DE',{weekday:'short',day:'2-digit',month:'2-digit'}).replace(/,$/,'');return (!dateTxt||d===dateTxt)&&(!timeStart||String(e.time||'').includes(timeStart))})||null}
async function enhanceCard(el){const box=ensureBox(el),e=eventForCard(el);if(!e)return;if(!e.location)return;const geo=await geocode(e.location);if(!geo)return;let weatherLine=box.querySelector('.smartline.weather');if(!weatherLine){weatherLine=document.createElement('div');weatherLine.className='smartline weather';weatherLine.textContent='🌦️ Wetter zum Terminbeginn wird geladen …';box.prepend(weatherLine)}let driveLine=box.querySelector('.smartline:not(.weather)');if(!driveLine){driveLine=document.createElement('div');driveLine.className='smartline';box.appendChild(driveLine)}if(currentPos){const km=hav(currentPos.lat,currentPos.lon,geo.lat,geo.lon),mins=driveEstimate(km),base=e.meetTime||e.meetingTime||e.treffzeit||e.time||'',depart=minusTime(base,mins+10);if(depart)driveLine.innerHTML=`🚗 ca. ${mins} Min · Abfahrt ${depart} Uhr <span style="opacity:.65;font-weight:650">(+10 Min Puffer)</span>`}else driveLine.textContent='📍 Standort aktualisieren für Abfahrtszeit'}
async function refreshCards(force=false){if(busy&&!force)return;busy=true;try{addBar();const cards=[...document.querySelectorAll('.card[data-event-key]')];cards.forEach(ensureBox);await Promise.all(cards.slice(0,40).map(c=>enhanceCard(c)))}finally{busy=false}}
addBar();setTimeout(()=>refreshCards(true),500);setTimeout(()=>locate(false),900);setInterval(()=>refreshCards(false),4000);document.addEventListener('click',()=>setTimeout(()=>refreshCards(false),150),{passive:true});setInterval(()=>{if(currentPos&&Date.now()-currentPos.at>5*60*1000)locate(false)},60000);setInterval(()=>{if(typeof render==='function')render()},60000);
})();